### ISSUE TITLE
Color changes not reflected instantly

### ISSUE THREAD

**Issue by pabueco** [pabueco/hue.tools#10]
Currently there is a CSS transition applied to the color cards and blocks. This means every change of the background color is smoothed by a transition. When doing small adjustments this feels kind of laggy. This is very noticable in the modify tool.

An easy fix would be to just remove the transitions from the affected elements.

**Comment by KappaPrajd** [comment]
I would like to tackle this :)

**Comment by KappaPrajd** [comment]
I created pull request #12 for this issue. Let me know what do you think about it.
