### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by fatesallow** [pabueco/hue.tools#11]
I love this tool! A dark mode toggle would be a great feature. Colors look so different when layered on black/white, so being able to toggle the background color helps see the colors properly.

**Comment by pabueco** [comment]
I can't believe I didn't think of this before. That's such a useful and quite important feature. 
Thank you very much for the suggestion @fatesallow!

**Comment by fatesallow** [comment]
@pabueco Oh good! I'm glad I mentioned it. Thanks for making this. It's super helpful!
