### ISSUE TITLE
Clearing any color input completely breaks the app

### ISSUE THREAD

**Issue by pabueco** [pabueco/hue.tools#5]

**Comment by KappaPrajd** [comment]
I would like to tackle this. What behavior do you expect after clearing input completely?

**Comment by pabueco** [comment]
That's great, thank you.

So I'm not completely sure what would be best. But I think it would be easiest to just default to black if the input is empty. 

I'm currently also not quite sure how invalid color values are handled. Showing an error might be too much, but maybe we could show a little warning icon (⚠️) on the color if the input is invalid somehow.

What do you think?

**Comment by pabueco** [comment]
That's great, thank you.

So I'm not completely sure what would be best. But I think it would be easiest to just default to black if the input is empty. 

I'm currently also not quite sure how invalid color values are handled. Showing an error might be too much, but maybe we could show a little warning icon (⚠️) on the color if the input is invalid somehow. But this is also not as important as this specific issue, so we could do this another time.

What do you think?

**Comment by KappaPrajd** [comment]
I agree with setting color to black after clearing the input, this should be pretty easy to do. I think adding the warning icon is also a good idea, I would maybe add a tooltip on hover saying "Invalid color" for better UX if that's okay for you.

**Comment by pabueco** [comment]
Sounds great!

**Comment by KappaPrajd** [comment]
I created the pull request #13 for this issue. I added some tweaks, darkened the input background if the value isn't a valid color to improve UX, let me know if that's okay for you.

**Comment by pabueco** [comment]
Thanks, nice idea. I checked the PR and just found a few minor things I would change.
